export const GET_PULL_REQUESTS_REPOSITORY = 'GET_PULL_REQUESTS_REPOSITORY';

export const LOAD_PROJECT_PULL_REQUESTS_SUCCESS = 'LOAD_PROJECT_PULL_REQUESTS_SUCCESS';

export const LOAD_PULL_REQUESTS_NO_PROJECT_SUCCESS = 'LOAD_PULL_REQUESTS_NO_PROJECT_SUCCESS';

export const ADDED_PULL_REQUEST_SUCCESS = "ADDED_PULL_REQUEST_SUCCESS";

export const ADDED_PULL_REQUEST_ERROR = "ADDED_PULL_REQUEST_ERROR";