// PULL REQUESTS CONSTANTS

export const GET_PULL_REQUESTS_REPOSITORY = 'GET_PULL_REQUESTS_REPOSITORY';

export const LOAD_PROJECT_PULL_REQUESTS_SUCCESS = 'LOAD_PROJECT_PULL_REQUESTS_SUCCESS';

export const LOAD_PULL_REQUESTS_NO_PROJECT_SUCCESS = 'LOAD_PULL_REQUESTS_NO_PROJECT_SUCCESS';

export const ADDED_PULL_REQUEST_SUCCESS = "ADDED_PULL_REQUEST_SUCCESS";

export const ADDED_PULL_REQUEST_ERROR = "ADDED_PULL_REQUEST_ERROR";

export const LOAD_EXTERNAL_PULL_REQUESTS_NO_PROJECT_SUCCESS = "LOAD_EXTERNAL_PULL_REQUESTS_NO_PROJECT_SUCCESS";

export const LOAD_EXTERNAL_PULL_REQUESTS_NO_PROJECT_ERROR = "LOAD_EXTERNAL_PULL_REQUESTS_NO_PROJECT_ERROR";

export const LOAD_PULL_REQUEST_SUCCESS = "LOAD_PULL_REQUEST_SUCCESS";

export const LOAD_PULL_REQUEST_ERROR = "LOAD_PULL_REQUEST_ERROR";

export const RESET_PROJECT_PULL_REQUESTS = "RESET_PROJECT_PULL_REQUESTS";

export const RESET_REPOSITORIES_NO_PROJECT = "RESET_REPOSITORIES_NO_PROJECT";

export const RESET_PULL_REQUESTS_NO_PROJECT = "RESET_PULL_REQUESTS_NO_PROJECT";

// REPOSITORIES CONSTANTS

export const LOAD_PROJECT_REPOSITORIES_SUCCESS = "LOAD_PROJECT_REPOSITORIES_SUCCESS";

export const LOAD_REPOSITORIES_NO_PROJECT_SUCCESS = "LOAD_REPOSITORIES_NO_PROJECT_SUCCESS";

export const ADDED_REPOSITORY_SUCCESS = "ADDED_REPOSITORY_SUCCESS";

export const ADDED_REPOSITORY_ERROR = "ADDED_REPOSITORY_ERROR";

export const LOAD_EXTERNAL_REPOSITORIES = "LOAD_EXTERNAL_REPOSITORIES";

export const LOAD_EXTERNAL_REPOSITORIES_ERROR = "LOAD_EXTERNAL_REPOSITORIES_ERROR";

export const RESET_PROJECT_REPOSITORIES = "RESET_PROJECT_REPOSITORIES";

// PROJECTS CONSTANTS

export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";

export const LOAD_PROJECTS_ERROR = "LOAD_PROJECTS_ERROR";

export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";

export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";

export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";

// AUTH CONSTANTS

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";